In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("number-of-deaths-by-risk-factor.csv", sep=",")

In [5]:
df

,Entity,Code,Year,Deaths - Unsafe water source - Sex: Both - Age: All Ages (Number),Deaths - Unsafe sanitation - Sex: Both - Age: All Ages (Number),Deaths - No access to handwashing facility - Sex: Both - Age: All Ages (Number),Deaths - Household air pollution from solid fuels - Sex: Both - Age: All Ages (Number),Deaths - Non-exclusive breastfeeding - Sex: Both - Age: All Ages (Number),Deaths - Discontinued breastfeeding - Sex: Both - Age: All Ages (Number),Deaths - Child wasting - Sex: Both - Age: All Ages (Number),...,Deaths - Air pollution - Sex: Both - Age: All Ages (Number),Deaths â€“ Outdoor air pollution (all ages) (IHME),Deaths - Diet low in fiber - Sex: Both - Age: All Ages (Number),Deaths - Diet high in sodium - Sex: Both - Age: All Ages (Number),Deaths - Diet low in legumes - Sex: Both - Age: All Ages (Number),Deaths - Diet low in calcium - Sex: Both - Age: All Ages (Number),Deaths - Diet high in red meat - Sex: Both - Age: All Ages (Number),Deaths - Diet low in whole grains - Sex: Both - Age: All Ages (Number),Deaths - Diet low in nuts and seeds - Sex: Both - Age: All Ages (Number),Deaths - Diet low in seafood omega-3 fatty acids - Sex: Both - Age: All Ages (Number)
0,Afghanistan,AFG,1990,7554.049543,5887.747628,5412.314513,22388.497233,3221.138842,156.097553,22778.849249,...,26598.006727,4383.83,2864.234512,2737.197934,3418.965194,181.287701,0.220484,11381.377345,7299.867330,6456.565238
1,Afghanistan,AFG,1991,7359.676749,5732.770160,5287.891103,22128.758206,3150.559597,151.539851,22292.691113,...,26379.532218,4426.36,2974.479775,2741.184956,3457.398250,184.251584,0.184714,11487.832390,7386.764303,6511.344276
2,Afghanistan,AFG,1992,7650.437822,5954.804987,5506.657363,22873.768789,3331.349048,156.609194,23102.197940,...,27263.127914,4568.91,3168.591633,2798.560245,3586.490291,191.318450,0.151354,11866.235572,7640.628526,6703.095594
3,Afghanistan,AFG,1993,10270.731383,7986.736613,7104.620351,25599.756284,4477.006100,206.834451,27902.669960,...,30495.561499,5080.29,3401.045056,2853.301679,3746.266658,199.767293,0.109392,12335.961682,7968.311853,6946.196824
4,Afghanistan,AFG,1994,11409.177112,8863.010065,8051.515953,28013.167200,5102.622054,233.930571,32929.005932,...,33323.161401,5499.23,3599.709735,2880.025765,3869.288402,206.619714,0.059103,12672.950191,8244.368430,7138.030745
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6463,Zimbabwe,ZWE,2013,4254.282075,2977.649750,3913.210510,7613.561005,1037.968042,59.150493,7703.062474,...,9593.033931,2053.58,619.391594,1018.389001,469.787520,182.630009,0.000311,2687.636261,2409.930182,1757.282549
6464,Zimbabwe,ZWE,2014,4098.769691,2856.426187,3809.245683,7429.446352,972.886327,54.334796,7401.059382,...,9387.193480,2030.92,604.168238,1016.407438,482.800746,184.379579,0.000756,2654.381923,2399.261581,1740.938755
6465,Zimbabwe,ZWE,2015,3921.291358,2717.735794,3688.442102,7267.029297,912.248164,50.255551,7100.476546,...,9189.336702,1994.91,594.347147,1019.971539,494.337563,188.020716,0.001512,2635.950107,2398.525219,1732.926445
6466,Zimbabwe,ZWE,2016,3802.257512,2624.315858,3603.179799,7134.595677,875.706009,47.719473,6823.766727,...,9092.577378,2030.88,592.092457,1032.181216,507.088683,192.913319,0.002787,2641.376815,2417.422521,1740.653975
6467,Zimbabwe,ZWE,2017,3796.070615,2612.122560,3579.352078,6982.337249,866.902012,46.816760,6609.236886,...,9020.941349,2112.19,595.869132,1049.402363,520.751472,196.849490,0.004705,2664.132572,2449.546229,1762.183897

In [8]:
df["Deaths - Unsafe water source - Sex: Both - Age: All Ages (Number)"].min()

0.00865019307122983

In [9]:
df["Deaths - Unsafe water source - Sex: Both - Age: All Ages (Number)"].median()

279.03169197819534

In [10]:
df["Deaths - Unsafe sanitation - Sex: Both - Age: All Ages (Number)"].median()

160.1965364741019

In [11]:
df["Deaths - No access to handwashing facility - Sex: Both - Age: All Ages (Number)"].median()

252.4990983515709

In [12]:
df["Deaths - Household air pollution from solid fuels - Sex: Both - Age: All Ages (Number)"].median()

1091.6711527653642

In [13]:
df["Deaths - Non-exclusive breastfeeding - Sex: Both - Age: All Ages (Number)"].median()

102.42830700851498

In [15]:
df["Deaths - Child wasting - Sex: Both - Age: All Ages (Number)"].median()

730.3462374675296

In [16]:
df["Deaths - Air pollution - Sex: Both - Age: All Ages (Number)"].median()

6125.098027840131

In [21]:
df["Entity"].describe()

count           6468
unique           231
top       Bangladesh
freq              28
Name: Entity, dtype: object

In [23]:
df.value_counts()

Entity       Code  Year  Deaths - Unsafe water source - Sex: Both - Age: All Ages (Number)  Deaths - Unsafe sanitation - Sex: Both - Age: All Ages (Number)  Deaths - No access to handwashing facility - Sex: Both - Age: All Ages (Number)  Deaths - Household air pollution from solid fuels - Sex: Both - Age: All Ages (Number)  Deaths - Non-exclusive breastfeeding - Sex: Both - Age: All Ages (Number)  Deaths - Discontinued breastfeeding - Sex: Both - Age: All Ages (Number)  Deaths - Child wasting - Sex: Both - Age: All Ages (Number)  Deaths - Child stunting - Sex: Both - Age: All Ages (Number)  Deaths - Low birth weight for gestation - Sex: Both - Age: All Ages (Number)  Deaths - Secondhand smoke - Sex: Both - Age: All Ages (Number)  Deaths - Alcohol use - Sex: Both - Age: All Ages (Number)  Deaths - Drug use - Sex: Both - Age: All Ages (Number)  Deaths - Diet low in fruits - Sex: Both - Age: All Ages (Number)  Deaths - Diet low in vegetables - Sex: Both - Age: All Ages (Number)  Deaths - Unsafe sex - Sex: Both - Age: All Ages (Number)  Deaths - Low physical activity - Sex: Both - Age: All Ages (Number)  Deaths - High fasting plasma glucose - Sex: Both - Age: All Ages (Number)  Deaths - High total cholesterol - Sex: Both - Age: All Ages (Number)  Deaths - High body-mass index - Sex: Both - Age: All Ages (Number)  Deaths - High systolic blood pressure - Sex: Both - Age: All Ages (Number)  Deaths - Smoking - Sex: Both - Age: All Ages (Number)  Deaths - Iron deficiency - Sex: Both - Age: All Ages (Number)  Deaths - Zinc deficiency - Sex: Both - Age: All Ages (Number)  Deaths - Vitamin A deficiency - Sex: Both - Age: All Ages (Number)  Deaths - Low bone mineral density - Sex: Both - Age: All Ages (Number)  Deaths - Air pollution - Sex: Both - Age: All Ages (Number)  Deaths â€“ Outdoor air pollution (all ages) (IHME)  Deaths - Diet low in fiber - Sex: Both - Age: All Ages (Number)  Deaths - Diet high in sodium - Sex: Both - Age: All Ages (Number)  Deaths - Diet low in legumes - Sex: Both - Age: All Ages (Number)  Deaths - Diet low in calcium - Sex: Both - Age: All Ages (Number)  Deaths - Diet high in red meat - Sex: Both - Age: All Ages (Number)  Deaths - Diet low in whole grains - Sex: Both - Age: All Ages (Number)  Deaths - Diet low in nuts and seeds - Sex: Both - Age: All Ages (Number)  Deaths - Diet low in seafood omega-3 fatty acids - Sex: Both - Age: All Ages (Number)
Zimbabwe     ZWE   2016  3802.257512                                                        2624.315858                                                      3603.179799                                                                      7134.595677                                                                             875.706009                                                                 47.719473                                                                 6823.766727                                                  1099.871279                                                   5441.209767                                                                   1761.316182                                                     7174.598012                                                1031.880274                                             3276.409022                                                       2525.950021                                                           16942.697763                                              810.425551                                                           10668.781189                                                               2384.867625                                                           5524.165987                                                         11096.182440                                                                8758.486720                                            319.692576                                                     139.690776                                                     950.215259                                                          244.719399                                                              9092.577378                                                  2030.88                                           592.092457                                                       1032.181216                                                        507.088683                                                         192.913319                                                         2.786927e-03                                                         2641.376815                                                             2417.422521                                                               1740.653975                                                                              1
Georgia      GEO   2006  10.328680                                                          10.662240                                                        15.528574                                                                        2438.528182                                                                             16.118533                                                                  0.707300                                                                  63.617001                                                    11.289446                                                     397.678624                                                                    1596.543145                                                     907.187372                                                 285.634604                                              4339.058041                                                       3249.768185                                                           194.386406                                                1662.738198                                                          10392.924317                                                               6893.121244                                                           7704.066620                                                         17653.632681                                                                6083.354365                                            3.895936                                                       2.411703                                                       6.454452                                                            68.426372                                                               4644.662271                                                  2267.11                                           1330.105919                                                      3972.745409                                                        1799.321754                                                        91.972500                                                          8.617266e-02                                                         5849.554934                                                             3352.889196                                                               2635.925226                                                                              1
Gambia       GMB   2005  763.879874                                                         568.074789                                                       578.067644                                                                       949.477303                                                                              95.889683                                                                  7.197715                                                                  1010.280864                                                  135.135935                                                    872.850286                                                                    279.886871                                                      321.961677                                                 65.940660                                               390.214528                                                        273.989383                                                            747.568265                                                101.964667                                                           761.307334                                                                 228.139033                                                            474.681356                                                          1266.656442                                                                 581.171879                                             124.994863                                                     29.926640                                                      249.154742                                                          44.158957                                                               1110.714947                                                  165.97                                            82.279876                                                        105.998500                                                         42.480969                                                          10.175203                                                          7.871463e-14                                                         346.734098                                                              246.520348                                                                200.846751                                                                               1
                   2006  721.459032                                                         535.882368                                                       556.646195                                                                       962.125201                                                                              89.228687                                                                  6.855979                                                                  964.581879                                                   125.289833                                                    874.572850                                                                    285.447139                                                      324.552414                                                 70.579773                                               406.189285                                                        285.473887                                                            817.773943                                                106.571073                                                           802.740821                                                                 234.956501                                                            500.849199                                                          1324.348378                                                                 595.055079                                             127.870382                                                     27.274727                                                      230.287130                                                          46.024273                                                               1129.966214                                                  172.80                                            82.526733                                                        116.592263                                                         47.901594                                                          10.497145                                                          8.220476e-14                                                         361.142399                                                              257.034346                                                                209.145319                                                                               1
                   2010  568.229431                                                         419.296170                                                       475.667746                                                                       981.893497                                                                              71.247724                                                                  5.508014                                                                  814.831430                                                   97.446147                                                     854.116002                                                                    292.880353                                                      290.475979                                                 86.208434                                               456.027955                                                        321.847378                                                            995.615108                                                122.265307                                                           956.196854                                                                 255.716501                                                            603.768919                                                          1519.165152                                                                 635.970421                                             124.685024                                                     17.338284                                                      192.973968                                                          52.745340                                                               1171.561884                                                  195.43                                            81.351330                                                        137.065028                                                         68.360728                                                          11.696524                                                          9.655091e-14                                                         405.023339                                                              289.712603                                                                235.044873                                                                               1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ..
Norway       NOR   2016  7.355717                                                           4.918203                                                         18.664106                                                                        19.992513                                                                               0.430275                                                                   0.062080                                                                  41.389124                                                    0.071294                                                      33.410380                                                                     381.249681                                                      524.735713                                                 405.882762                                              754.121485                                                        1072.262560                                                           132.429124                                                1209.725446                                                          5747.170779                                                                3879.525997                                                           3238.445380                                                         6772.220154                                                                 6019.759172                                            0.310804                                                       0.043405                                                       0.239529                                                            495.341551                                                              1128.426024                                                  1126.50                                           722.815994                                                       986.936949                                                         501.505976                                                         209.009202                                                         4.480572e+01                                                         1716.362879                                                             1225.505004                                                               738.490482                                                                               1

In [24]:
df[1:45]

,Entity,Code,Year,Deaths - Unsafe water source - Sex: Both - Age: All Ages (Number),Deaths - Unsafe sanitation - Sex: Both - Age: All Ages (Number),Deaths - No access to handwashing facility - Sex: Both - Age: All Ages (Number),Deaths - Household air pollution from solid fuels - Sex: Both - Age: All Ages (Number),Deaths - Non-exclusive breastfeeding - Sex: Both - Age: All Ages (Number),Deaths - Discontinued breastfeeding - Sex: Both - Age: All Ages (Number),Deaths - Child wasting - Sex: Both - Age: All Ages (Number),...,Deaths - Air pollution - Sex: Both - Age: All Ages (Number),Deaths â€“ Outdoor air pollution (all ages) (IHME),Deaths - Diet low in fiber - Sex: Both - Age: All Ages (Number),Deaths - Diet high in sodium - Sex: Both - Age: All Ages (Number),Deaths - Diet low in legumes - Sex: Both - Age: All Ages (Number),Deaths - Diet low in calcium - Sex: Both - Age: All Ages (Number),Deaths - Diet high in red meat - Sex: Both - Age: All Ages (Number),Deaths - Diet low in whole grains - Sex: Both - Age: All Ages (Number),Deaths - Diet low in nuts and seeds - Sex: Both - Age: All Ages (Number),Deaths - Diet low in seafood omega-3 fatty acids - Sex: Both - Age: All Ages (Number)
1,Afghanistan,AFG,1991,7359.676749,5732.770160,5287.891103,22128.758206,3150.559597,151.539851,22292.691113,...,26379.532218,4426.36,2974.479775,2741.184956,3457.398250,184.251584,0.184714,11487.832390,7386.764303,6511.344276
2,Afghanistan,AFG,1992,7650.437822,5954.804987,5506.657363,22873.768789,3331.349048,156.609194,23102.197940,...,27263.127914,4568.91,3168.591633,2798.560245,3586.490291,191.318450,0.151354,11866.235572,7640.628526,6703.095594
3,Afghanistan,AFG,1993,10270.731383,7986.736613,7104.620351,25599.756284,4477.006100,206.834451,27902.669960,...,30495.561499,5080.29,3401.045056,2853.301679,3746.266658,199.767293,0.109392,12335.961682,7968.311853,6946.196824
4,Afghanistan,AFG,1994,11409.177112,8863.010065,8051.515953,28013.167200,5102.622054,233.930571,32929.005932,...,33323.161401,5499.23,3599.709735,2880.025765,3869.288402,206.619714,0.059103,12672.950191,8244.368430,7138.030745
5,Afghanistan,AFG,1995,12676.647424,9840.848680,8770.686294,29062.618787,5402.660379,262.793340,35631.997028,...,34511.845284,5641.29,3732.598460,2892.221692,3935.209932,211.137298,0.039922,12854.592679,8375.861883,7225.040846
6,Afghanistan,AFG,1996,12154.942315,9426.896445,8610.686857,29407.321601,5263.644458,253.668181,36114.593233,...,34952.101583,5739.07,3877.026009,2905.798225,4019.906785,215.778490,0.026291,13089.157280,8537.651676,7336.080630
7,Afghanistan,AFG,1997,12329.131710,9553.555998,8722.943079,29674.398315,5271.771800,258.134146,36749.117453,...,35306.566595,5828.94,4017.069696,2919.683894,4104.371202,220.586247,0.017090,13326.500377,8694.523034,7446.826074
8,Afghanistan,AFG,1998,12133.609541,9390.042030,8621.884918,29807.453214,5165.923779,254.708078,36569.465573,...,35360.168867,5751.54,4137.050160,2925.391235,4173.597768,224.793817,0.010725,13516.547571,8818.249272,7532.322210
9,Afghanistan,AFG,1999,11990.396328,9268.489611,8502.729990,29484.612215,5044.307573,251.898824,36124.046557,...,35040.349506,5756.43,4211.727042,2936.213764,4201.930953,229.298613,0.007501,13584.239432,8867.619444,7553.269512
10,Afghanistan,AFG,2000,11121.653284,8588.517136,7910.366272,28329.380089,4566.918647,235.101472,34320.364596,...,33714.056093,5587.68,4264.486388,2928.850878,4205.939705,234.869750,0.002476,13621.076956,8869.121379,7536.488937
11,Afghanistan,AFG,2001,10431.364445,8046.884118,7501.548129,27721.641256,4219.420003,220.529327,32430.506891,...,33084.898808,5569.97,4336.951106,2924.407671,4229.206133,241.362871,0.001223,13729.218376,8920.552739,7560.790625
12,Afghanistan,AFG,2002,9764.768756,7522.617843,7055.322090,26679.508332,3852.417277,207.900393,30516.319451,...,32052.897075,5580.75,4372.057938,2929.456819,4232.325602,246.525387,0.000833,13770.831626,8901.792260,7536.660849
13,Afghanistan,AFG,2003,11510.492710,8853.838865,8214.459990,28325.886808,4184.981616,254.024088,30053.870976,...,34229.476605,6111.07,4404.297668,2935.115511,4233.956804,251.606940,0.000588,13814.104883,8878.598378,7511.840020
14,Afghanistan,AFG,2004,11656.614656,8950.642810,8331.270817,28511.343486,4067.087139,262.000727,29568.253876,...,34462.341433,6159.58,4422.704373,2955.081728,4219.626890,256.127808,0.000221,13808.042550,8832.863909,7471.834547
15,Afghanistan,AFG,2005,10973.736325,8410.948806,7928.463722,27621.503383,3761.322094,245.140693,27799.719164,...,33603.467346,6189.71,4439.091537,2958.574389,4201.880619,260.255967,0.000146,13785.140783,8782.006155,7423.576520
16,Afghanistan,AFG,2006,10040.772962,7673.530946,7393.873325,26765.726784,3549.869090,216.945204,26233.635650,...,32759.439552,6202.75,4441.160448,2964.409777,4173.446322,264.505782,0.000095,13729.953193,8718.309024,7376.349859
17,Afghanistan,AFG,2007,8884.667717,6776.148232,6631.322021,25149.205084,3219.282623,182.524079,24012.813339,...,31145.728255,6204.82,4426.714722,2971.581700,4131.931236,268.320364,0.000068,13631.425581,8625.936713,7310.497600
18,Afghanistan,AFG,2008,7703.609482,5857.353606,5854.381952,23781.765349,2983.864501,146.726804,21793.394058,...,29696.643289,6123.82,4448.881462,2995.320943,4123.036438,273.533973,0.000051,13640.892613,8597.317493,7296.478130
19,Afghanistan,AFG,2009,6842.309980,5177.564915,5279.978576,22528.507350,2869.020279,121.403031,20333.934815,...,28432.975343,6112.64,4438.190384,3019.912793,4089.552767,277.195326,0.000043,13579.135062,8507.719886,7243.441162
20,Afghanistan,AFG,2010,6436.211217,4843.771106,4992.484763,21807.390332,2796.504240,109.114436,18946.894669,...,27754.109874,6154.12,4439.424560,3049.005496,4068.898054,280.562629,0.000051,13534.739617,8438.243774,7201.020147
21,Afghanistan,AFG,2011,6023.629124,4507.041694,4725.821542,20955.695805,2734.032895,100.096919,17867.741125,...,27174.744310,6425.95,4475.310601,3097.710300,4082.091713,285.343363,0.000062,13614.033652,8452.451444,7226.579103
22,Afghanistan,AFG,2012,5613.053154,4170.828020,4449.080788,20260.869267,2642.066131,92.586649,16980.380109,...,26529.230516,6475.42,4503.468397,3152.690488,4092.158597,290.107012,0.000087,13698.734898,8454.321712,7247.992421
23,Afghanistan,AFG,2013,5649.755736,4166.686083,4474.557454,20236.442784,2644.288520,95.121839,16308.282170,...,26468.199306,6438.87,4554.604330,3214.655896,4124.421263,296.020549,0.000128,13860.627405,8507.319690,7307.714600
24,Afghanistan,AFG,2014,5533.135738,4048.986437,4391.708269,20044.816335,2620.398334,94.467087,15825.362245,...,26251.144599,6414.25,4612.723224,3272.323115,4163.327291,302.363933,0.000221,14065.398294,8583.175662,7382.178815
25,Afghanistan,AFG,2015,5300.424440,3843.622727,4231.835720,19462.377450,2541.753356,91.689134,15344.889656,...,26033.718409,6780.26,4679.879060,3316.445516,4213.499060,308.031696,0.000359,14242.305348,8687.274664,7466.863916
26,Afghanistan,AFG,2016,5158.400864,3723.506721,4126.336468,19427.558233,2438.076606,90.904173,14695.046711,...,25780.218287,6562.98,4761.847005,3379.034511,4278.047894,315.989398,0.000618,14511.810754,8836.670338,7584.147763
27,Afghanistan,AFG,2017,5256.649276,3783.111117,4156.209013,19397.378213,2422.369175,94.118135,14575.269211,...,26054.195719,6872.06,4889.502247,3457.083571,4384.887948,325.722066,0.000999,14884.958403,9074.388004,7775.129667
28,Albania,ALB,1990,50.125767,30.950057,42.276879,1337.654648,160.275338,1.895415,1022.820898,...,1938.678869,626.95,272.704477,1816.422489,244.272137,25.055265,0.012076,1232.756618,673.508094,541.963566
29,Albania,ALB,1991,51.042750,31.828051,44.275074,1392.734624,160.726973,1.948038,1006.071416,...,2021.316572,654.88,290.715104,1870.857333,255.502880,26.082971,0.014823,1302.835657,708.917766,568.944299
30,Albania,ALB,1992,48.824502,30.764896,43.190281,1361.996449,155.045020,1.825976,980.300974,...,1971.115037,634.39,290.304137,1806.213616,250.106279,25.960817,0.016317,1287.072351,698.305051,558.343301
31,Albania,ALB,1993,43.786246,27.730975,40.683141,1304.792371,146.126790,1.593158,933.009336,...,1890.142195,609.17,284.675734,1660.755772,241.311098,25.437007,0.019054,1253.622846,678.470302,540.245965
32,Albania,ALB,1994,53.146513,33.653502,38.385929,1215.522470,138.606953,1.840297,866.910003,...,1774.624691,581.23,276.082044,1513.741074,231.440357,23.911661,0.025239,1214.643072,654.388504,518.917997
33,Albania,ALB,1995,26.108352,16.428292,31.495981,1182.102319,116.434339,0.868248,741.495108,...,1740.547586,580.21,286.639450,1499.888318,238.710989,23.135016,0.033890,1271.456002,679.184748,536.770134
34,Albania,ALB,1996,20.995243,13.060130,27.243518,1174.919850,101.815845,0.674460,635.854703,...,1754.374294,601.70,306.167842,1540.190855,254.132599,22.961140,0.049480,1377.057266,727.681384,573.390364
35,Albania,ALB,1997,17.336995,10.657216,23.412294,1136.569996,87.034648,0.534999,535.348597,...,1727.981255,613.38,318.212501,1524.307202,262.154537,22.849199,0.064283,1444.269824,756.252170,594.324473
36,Albania,ALB,1998,14.382585,8.654031,19.898420,1085.878540,72.702194,0.422682,440.117565,...,1684.404653,619.67,327.968484,1482.120250,268.141328,23.076954,0.086479,1491.271493,776.984811,608.680604
37,Albania,ALB,1999,13.004882,7.549786,17.377020,1041.806268,66.367654,0.373948,378.371129,...,1651.240183,629.68,335.565255,1424.671827,273.369991,23.244788,0.124138,1526.866006,794.522028,619.494112
38,Albania,ALB,2000,11.045852,6.239349,14.528250,994.479073,53.601213,0.318404,316.771675,...,1601.176755,626.14,343.160512,1379.661243,279.746440,22.601660,0.164137,1557.432092,814.501030,632.221802
39,Albania,ALB,2001,9.122746,4.893006,11.708222,938.463630,38.634360,0.245699,224.660906,...,1546.512344,626.39,349.700374,1335.490315,285.714509,22.312970,0.217512,1584.162988,831.469778,642.156834
40,Albania,ALB,2002,7.837641,3.982496,10.108352,921.315180,31.399748,0.199389,176.714350,...,1553.416625,649.88,366.460567,1337.471245,301.037652,22.178739,0.284729,1661.439104,875.619914,673.259789
41,Albania,ALB,2003,6.905142,3.318331,8.881071,918.265970,25.722090,0.167278,140.593392,...,1576.379509,675.57,384.775795,1348.388066,318.518114,22.053080,0.365907,1749.471020,925.850908,709.401411
42,Albania,ALB,2004,6.346128,2.904866,7.802275,896.638155,21.305118,0.148913,112.398715,...,1577.259504,697.63,396.982123,1380.062412,331.493874,22.219684,0.462195,1809.481572,960.656018,733.888675
43,Albania,ALB,2005,5.942308,2.672627,6.888944,866.816178,18.182142,0.135662,93.640673,...,1552.906152,702.31,400.904569,1382.474610,338.234259,21.819942,0.548470,1829.947574,975.081491,742.648264
44,Albania,ALB,2006,5.487749,2.483431,6.167794,822.979122,15.517889,0.117291,79.727360,...,1517.519881,710.02,398.494330,1374.888051,340.167692,21.577180,0.636448,1824.978408,975.652346,740.318847

In [25]:
df[df['Deaths - Household air pollution from solid fuels - Sex: Both - Age: All Ages (Number)'] > 3000]

,Entity,Code,Year,Deaths - Unsafe water source - Sex: Both - Age: All Ages (Number),Deaths - Unsafe sanitation - Sex: Both - Age: All Ages (Number),Deaths - No access to handwashing facility - Sex: Both - Age: All Ages (Number),Deaths - Household air pollution from solid fuels - Sex: Both - Age: All Ages (Number),Deaths - Non-exclusive breastfeeding - Sex: Both - Age: All Ages (Number),Deaths - Discontinued breastfeeding - Sex: Both - Age: All Ages (Number),Deaths - Child wasting - Sex: Both - Age: All Ages (Number),...,Deaths - Air pollution - Sex: Both - Age: All Ages (Number),Deaths â€“ Outdoor air pollution (all ages) (IHME),Deaths - Diet low in fiber - Sex: Both - Age: All Ages (Number),Deaths - Diet high in sodium - Sex: Both - Age: All Ages (Number),Deaths - Diet low in legumes - Sex: Both - Age: All Ages (Number),Deaths - Diet low in calcium - Sex: Both - Age: All Ages (Number),Deaths - Diet high in red meat - Sex: Both - Age: All Ages (Number),Deaths - Diet low in whole grains - Sex: Both - Age: All Ages (Number),Deaths - Diet low in nuts and seeds - Sex: Both - Age: All Ages (Number),Deaths - Diet low in seafood omega-3 fatty acids - Sex: Both - Age: All Ages (Number)
0,Afghanistan,AFG,1990,7554.049543,5887.747628,5412.314513,22388.497233,3221.138842,156.097553,22778.849249,...,26598.006727,4383.83,2864.234512,2737.197934,3418.965194,181.287701,0.220484,11381.377345,7299.867330,6456.565238
1,Afghanistan,AFG,1991,7359.676749,5732.770160,5287.891103,22128.758206,3150.559597,151.539851,22292.691113,...,26379.532218,4426.36,2974.479775,2741.184956,3457.398250,184.251584,0.184714,11487.832390,7386.764303,6511.344276
2,Afghanistan,AFG,1992,7650.437822,5954.804987,5506.657363,22873.768789,3331.349048,156.609194,23102.197940,...,27263.127914,4568.91,3168.591633,2798.560245,3586.490291,191.318450,0.151354,11866.235572,7640.628526,6703.095594
3,Afghanistan,AFG,1993,10270.731383,7986.736613,7104.620351,25599.756284,4477.006100,206.834451,27902.669960,...,30495.561499,5080.29,3401.045056,2853.301679,3746.266658,199.767293,0.109392,12335.961682,7968.311853,6946.196824
4,Afghanistan,AFG,1994,11409.177112,8863.010065,8051.515953,28013.167200,5102.622054,233.930571,32929.005932,...,33323.161401,5499.23,3599.709735,2880.025765,3869.288402,206.619714,0.059103,12672.950191,8244.368430,7138.030745
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6463,Zimbabwe,ZWE,2013,4254.282075,2977.649750,3913.210510,7613.561005,1037.968042,59.150493,7703.062474,...,9593.033931,2053.58,619.391594,1018.389001,469.787520,182.630009,0.000311,2687.636261,2409.930182,1757.282549
6464,Zimbabwe,ZWE,2014,4098.769691,2856.426187,3809.245683,7429.446352,972.886327,54.334796,7401.059382,...,9387.193480,2030.92,604.168238,1016.407438,482.800746,184.379579,0.000756,2654.381923,2399.261581,1740.938755
6465,Zimbabwe,ZWE,2015,3921.291358,2717.735794,3688.442102,7267.029297,912.248164,50.255551,7100.476546,...,9189.336702,1994.91,594.347147,1019.971539,494.337563,188.020716,0.001512,2635.950107,2398.525219,1732.926445
6466,Zimbabwe,ZWE,2016,3802.257512,2624.315858,3603.179799,7134.595677,875.706009,47.719473,6823.766727,...,9092.577378,2030.88,592.092457,1032.181216,507.088683,192.913319,0.002787,2641.376815,2417.422521,1740.653975
6467,Zimbabwe,ZWE,2017,3796.070615,2612.122560,3579.352078,6982.337249,866.902012,46.816760,6609.236886,...,9020.941349,2112.19,595.869132,1049.402363,520.751472,196.849490,0.004705,2664.132572,2449.546229,1762.183897

In [27]:
df_child = df[df['Deaths - Child wasting - Sex: Both - Age: All Ages (Number)'] > 22000]

In [28]:
df_child.value_counts(df_child['Entity'])

Entity
North Africa and Middle East                        28
Pakistan                                            28
India                                               28
Indonesia                                           28
Latin America and Caribbean                         28
Low SDI                                             28
Low-middle SDI                                      28
Madagascar                                          28
World                                               28
Democratic Republic of Congo                        28
Middle SDI                                          28
Chad                                                28
Niger                                               28
Nigeria                                             28
Ethiopia                                            28
Central Sub-Saharan Africa                          28
Eastern Sub-Saharan Africa                          28
South Asia                                          28
Western Sub-Saharan Africa                          28
Southeast Asia                                      28
Southeast Asia, East Asia, and Oceania              28
Sub-Saharan Africa                                  28
East Asia                                           25
Bangladesh                                          24
Tanzania                                            23
China                                               23
Angola                                              23
Somalia                                             22
High-middle SDI                                     21
Southern Sub-Saharan Africa                         20
Afghanistan                                         18
Sudan                                               18
Burkina Faso                                        18
Mali                                                17
Central Latin America                               16
Myanmar                                             15
Brazil                                              13
Yemen                                               13
Tropical Latin America                              13
Kenya                                               12
Egypt                                               11
Mozambique                                          11
Central Europe, Eastern Europe, and Central Asia    11
Philippines                                         10
Uganda                                               9
North Korea                                          8
Central Asia                                         8
Guinea                                               6
Mexico                                               6
Nepal                                                6
Malawi                                               5
Rwanda                                               3
Andean Latin America                                 3
South Africa                                         2
dtype: int64

In [30]:
df_air = df[df['Deaths - Air pollution - Sex: Both - Age: All Ages (Number)'] > 30000]

In [31]:
df_air.value_counts(df_air['Entity'])

Entity
World                                               28
Western Sub-Saharan Africa                          28
Latin America and Caribbean                         28
Japan                                               28
Indonesia                                           28
India                                               28
High-middle SDI                                     28
High-income Asia Pacific                            28
High-income                                         28
High SDI                                            28
Germany                                             28
Ethiopia                                            28
Egypt                                               28
Eastern Sub-Saharan Africa                          28
Eastern Europe                                      28
East Asia                                           28
Democratic Republic of Congo                        28
China                                               28
Central Sub-Saharan Africa                          28
Central Latin America                               28
Central Europe, Eastern Europe, and Central Asia    28
Central Europe                                      28
Central Asia                                        28
Brazil                                              28
Bangladesh                                          28
Low SDI                                             28
Low-middle SDI                                      28
Russia                                              28
Philippines                                         28
Southeast Asia                                      28
Middle SDI                                          28
South Asia                                          28
Vietnam                                             28
Ukraine                                             28
Western Europe                                      28
Pakistan                                            28
Sub-Saharan Africa                                  28
United States                                       28
North America                                       28
Tropical Latin America                              28
North Africa and Middle East                        28
Nigeria                                             28
Myanmar                                             28
Southeast Asia, East Asia, and Oceania              28
Turkey                                              26
Mexico                                              25
Southern Sub-Saharan Africa                         23
Italy                                               21
North Korea                                         17
United Kingdom                                      15
Afghanistan                                         15
England                                              9
South Africa                                         8
Poland                                               8
Tanzania                                             7
Thailand                                             1
dtype: int64

In [34]:
df_breath = df[df['Deaths - Discontinued breastfeeding - Sex: Both - Age: All Ages (Number)'] > 250]

In [35]:
df_brath.value_counts(df_brath['Entity'])

Entity
Low-middle SDI                                      28
World                                               28
Latin America and Caribbean                         28
India                                               28
Middle SDI                                          28
Ethiopia                                            28
Niger                                               28
Nigeria                                             28
North Africa and Middle East                        28
Pakistan                                            28
Eastern Sub-Saharan Africa                          28
Democratic Republic of Congo                        28
Low SDI                                             28
South Asia                                          28
Southeast Asia                                      28
Southeast Asia, East Asia, and Oceania              28
Southern Sub-Saharan Africa                         28
Sub-Saharan Africa                                  28
Central Sub-Saharan Africa                          28
Western Sub-Saharan Africa                          28
Indonesia                                           27
Chad                                                26
Angola                                              25
South Africa                                        25
Cameroon                                            24
Yemen                                               24
Philippines                                         22
Brazil                                              21
Tropical Latin America                              21
China                                               20
East Asia                                           20
Somalia                                             20
High-middle SDI                                     17
Central Latin America                               17
Mali                                                12
Egypt                                               12
Mexico                                              10
Bangladesh                                          10
Tanzania                                            10
Central Europe, Eastern Europe, and Central Asia     9
Turkey                                               9
Caribbean                                            9
Madagascar                                           9
Sudan                                                8
Central Asia                                         7
Afghanistan                                          7
Kenya                                                5
Malawi                                               4
Morocco                                              4
Andean Latin America                                 4
Haiti                                                1
dtype: int64

In [38]:
gdf = df[df["Entity"] == "Russia"]
gdf

,Entity,Code,Year,Deaths - Unsafe water source - Sex: Both - Age: All Ages (Number),Deaths - Unsafe sanitation - Sex: Both - Age: All Ages (Number),Deaths - No access to handwashing facility - Sex: Both - Age: All Ages (Number),Deaths - Household air pollution from solid fuels - Sex: Both - Age: All Ages (Number),Deaths - Non-exclusive breastfeeding - Sex: Both - Age: All Ages (Number),Deaths - Discontinued breastfeeding - Sex: Both - Age: All Ages (Number),Deaths - Child wasting - Sex: Both - Age: All Ages (Number),...,Deaths - Air pollution - Sex: Both - Age: All Ages (Number),Deaths â€“ Outdoor air pollution (all ages) (IHME),Deaths - Diet low in fiber - Sex: Both - Age: All Ages (Number),Deaths - Diet high in sodium - Sex: Both - Age: All Ages (Number),Deaths - Diet low in legumes - Sex: Both - Age: All Ages (Number),Deaths - Diet low in calcium - Sex: Both - Age: All Ages (Number),Deaths - Diet high in red meat - Sex: Both - Age: All Ages (Number),Deaths - Diet low in whole grains - Sex: Both - Age: All Ages (Number),Deaths - Diet low in nuts and seeds - Sex: Both - Age: All Ages (Number),Deaths - Diet low in seafood omega-3 fatty acids - Sex: Both - Age: All Ages (Number)
4704,Russia,RUS,1990,895.378366,818.370293,588.972853,524.195174,1043.927457,86.348332,3815.516439,...,108602.106869,108885.91,42497.517866,88399.254105,49495.999226,5842.711412,601.500623,178404.240567,117158.983993,71072.868104
4705,Russia,RUS,1991,805.880624,734.973512,556.300872,494.371335,916.775275,75.314134,3435.160694,...,111504.916120,111832.08,43822.375355,89454.081142,50979.348323,5942.001863,588.950057,181414.308554,119091.395065,72697.841587
4706,Russia,RUS,1992,739.474241,671.215012,552.041541,486.403348,805.047663,64.468222,3101.911467,...,120036.485477,120421.24,48003.712092,95642.940310,55962.779755,6270.167925,603.383679,196059.785863,128577.188223,79355.212397
4707,Russia,RUS,1993,787.276532,712.796849,638.511346,554.498885,817.187734,60.009238,3136.033429,...,143343.547268,143807.55,58844.089234,113353.633427,68840.648368,7141.910815,663.716427,237142.647299,155274.501492,97291.544783
4708,Russia,RUS,1994,810.328729,733.107374,700.195663,597.019967,777.701717,55.513790,2948.186192,...,155634.765169,156115.56,65792.023136,123030.499743,76868.543042,7601.267026,650.052137,262507.172159,170952.040614,109470.624144
4709,Russia,RUS,1995,755.285444,681.869403,676.018740,540.242996,712.274427,52.868910,2716.571772,...,143783.079136,144222.48,62985.038253,115504.086865,72971.797199,7298.221597,546.906652,248737.175098,161343.473960,104938.741105
4710,Russia,RUS,1996,663.255905,598.437819,630.018341,488.713910,630.107573,47.263264,2444.426603,...,137808.626869,138268.73,59495.409554,107889.170610,68159.982137,7018.057000,446.150245,233918.134578,151146.242122,99894.365737
4711,Russia,RUS,1997,605.861609,547.899827,604.613692,451.066080,607.131310,44.246088,2348.789763,...,131897.404282,132356.63,56657.906710,102268.682307,64275.206713,6838.073711,368.801246,223110.002818,143405.035351,96018.057817
4712,Russia,RUS,1998,580.507047,525.076347,603.034124,434.491908,563.795788,41.992300,2211.721742,...,130026.196541,130473.95,56400.059565,100611.374193,63494.524658,6873.796815,320.509008,221723.248683,142040.999951,96181.740533
4713,Russia,RUS,1999,596.573975,539.247259,671.338191,467.151182,549.572705,40.538588,2181.207233,...,140183.814676,140654.52,62122.443838,108470.441402,69819.780833,7353.504988,305.765674,242325.084665,155712.216739,106241.276038
4714,Russia,RUS,2000,556.438605,503.746384,728.081271,477.691905,519.461865,36.074635,2056.143436,...,143211.266670,143655.04,65379.464837,112904.320181,73598.527983,7558.560799,295.679514,254354.973239,163852.757538,112159.905240
4715,Russia,RUS,2001,510.157429,463.057129,757.052882,507.216910,504.509367,33.155718,1989.959132,...,148608.866247,149017.07,66672.835378,114543.183502,75143.370509,7616.528291,284.676229,259079.794021,167580.897813,114669.284475
4716,Russia,RUS,2002,459.550976,417.490974,780.692630,571.098813,463.334313,29.909053,1846.632788,...,154122.200685,154464.70,68725.070886,117934.285853,77666.199110,7741.716933,286.564756,266802.630214,173711.428615,118422.347044
4717,Russia,RUS,2003,414.834954,376.281976,791.529980,666.569025,436.467770,27.509133,1767.583612,...,155615.276921,155834.63,69601.990408,119369.147364,78895.363809,7788.087203,294.756385,269121.259700,176669.682245,119436.618917
4718,Russia,RUS,2004,363.721950,327.419527,770.131592,735.697716,399.905488,24.963342,1650.508229,...,149742.242503,149825.49,67769.656518,116510.595278,77058.349968,7562.838085,300.994269,260217.224441,172129.858503,115284.798186
4719,Russia,RUS,2005,328.762869,292.941365,780.080449,848.195464,367.655609,22.307990,1559.512411,...,150585.611098,150527.11,69773.899779,120574.311809,79794.553730,7739.913122,333.343721,266265.359305,178191.450475,117653.713488
4720,Russia,RUS,2006,279.100934,248.375968,706.927755,782.651614,353.472434,19.661959,1471.831276,...,140319.886672,140263.16,63147.207099,111444.516363,72443.754772,7222.144762,336.051681,239885.901272,162920.572445,105558.885918
4721,Russia,RUS,2007,249.063316,219.711716,662.351381,749.834253,341.424897,17.935365,1387.551789,...,134428.888102,134373.70,59558.319368,107190.582129,68686.841478,6916.266148,354.117814,225113.869999,155133.210322,98527.471161
4722,Russia,RUS,2008,230.924799,201.547626,649.714556,707.165787,311.560907,16.600159,1275.346341,...,135028.690810,135019.81,59417.003184,108587.203979,68989.710046,6940.916884,395.520341,223503.464279,156008.156638,97200.659423
4723,Russia,RUS,2009,214.677223,185.379634,615.732595,647.518739,287.800125,15.631055,1184.376716,...,127978.220501,128002.66,56701.649099,104139.172549,65813.447735,6785.199087,411.318006,210805.005227,148649.806601,91715.805638
4724,Russia,RUS,2010,205.040841,175.065928,601.711570,614.959512,256.737627,14.479556,1074.292836,...,126281.197576,126333.07,56965.379545,105237.838512,66309.648173,6881.305792,450.668005,210449.834896,149883.523431,91404.206079
4725,Russia,RUS,2011,200.682004,168.921262,568.737302,555.258158,274.428608,14.434514,1116.660950,...,116835.720647,116914.16,53095.186130,98827.238371,61874.902147,6547.114072,459.971003,194698.062384,140099.812961,84309.757057
4726,Russia,RUS,2012,203.889249,169.112074,558.777445,524.742758,311.756982,15.208468,1238.149473,...,111204.007288,111293.52,51285.080604,96630.953165,59824.932785,6492.007630,491.537867,187633.690860,135887.375599,80778.593142
4727,Russia,RUS,2013,195.945626,159.508535,541.650511,486.271498,286.518827,14.044254,1149.341239,...,107161.296278,107282.14,49726.711168,94647.356646,58071.348762,6422.945153,524.950562,181962.382615,132061.781203,77618.486598
4728,Russia,RUS,2014,188.532874,151.736834,537.791990,473.097217,245.287834,12.315816,1015.406340,...,104465.944222,104595.96,49599.136675,95514.275574,57982.728113,6532.663954,577.746051,182534.205539,131900.544994,76944.981180
4729,Russia,RUS,2015,172.155163,137.214629,505.715686,437.306983,192.721778,9.839698,843.916876,...,103877.871638,104063.56,48536.143413,94194.998479,56731.342465,6509.174235,605.455505,179520.919417,129472.673798,75077.635513
4730,Russia,RUS,2016,160.816219,127.314238,478.769494,412.635852,168.025443,8.761078,780.306204,...,100111.467833,100301.57,47611.525348,92898.859657,55675.228776,6430.065428,622.349568,176535.592002,127155.633131,73387.187289
4731,Russia,RUS,2017,155.526737,122.517173,470.678197,381.849080,151.052688,8.204329,715.667186,...,99392.162297,99613.01,47504.174028,93047.761776,55654.616380,6380.007771,627.173873,175951.790484,126752.280345,72963.088242

In [39]:
gdf["Deaths - Unsafe sanitation - Sex: Both - Age: All Ages (Number)"].median()

351.85075141015705

In [40]:
gdf["Deaths - Unsafe water source - Sex: Both - Age: All Ages (Number)"].median()

389.2784517205122

In [41]:
gdf["Deaths - No access to handwashing facility - Sex: Both - Age: All Ages (Number)"].median()

622.87546782117

In [42]:
gdf["Deaths - Child wasting - Sex: Both - Age: All Ages (Number)"].median()

1709.0459201321753